// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var AvoInspector = require("avo-inspector");

var jsMapperConstantArray = [
  /* tuple */[
    -81877157,
    "staging"
  ],
  /* tuple */[
    3404213,
    "dev"
  ],
  /* tuple */[
    892859319,
    "prod"
  ]
];

function make(apiKey, env, version, param) {
  return new AvoInspector.AvoInspector({
              apiKey: apiKey,
              env: Js_mapperRt.binarySearch(3, env, jsMapperConstantArray),
              version: version
            });
}

function trackSchemaFromEvent(prim, prim$1, prim$2) {
  prim.trackSchemaFromEvent(prim$1, prim$2);
  
}

exports.make = make;
exports.trackSchemaFromEvent = trackSchemaFromEvent;
/* avo-inspector Not a pure module */
