// Generated by ReScript, PLEASE EDIT WITH CARE


function setNetworkTimeout(timeout) {
  ((require("avo-inspector").AvoInspector.networkTimeout = timeout));
}

export {
  setNetworkTimeout ,
}
/* No side effect */
