name: Avo Inspector

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Build Avo Inspector package
        run: yarn build

      - name: Test Source
        run: |
          yarn test:browser src/ --silent
